ingress:
  enabled: true
  host : haryo.example.com
  servicePort: 8080
postgres:
  image: postgres:15
  database: app
  username: user
  password: pass

redis:
  image: redis:7-alpine

kafka:
  image: apache/kafka:3.9.1

app:
  replicas: 2

  image:
    repository: 750004260360.dkr.ecr.us-east-1.amazonaws.com/springboot-app-service
    tag: f37fc26ae65c69482efc3c7977655c19d8eedf77
    pullPolicy: IfNotPresent

  springProfile: docker

jwt:
  secret: 45fa208eef62571c5b7f975c4bf7695d
  expiration: "3600000"