apiVersion: argoproj.io/v1alpha1
kind: Application

metadata:
  name: springboot-app
  namespace: argocd

spec:
  project: default

  source:
    repoURL: https://github.com/haryokuncoro/springboot-template-gitops.git
    targetRevision: main

    path: helm/springboot-app

    helm:
      valueFiles:
        - ../../environments/dev/values.yaml

  destination:
    server: https://kubernetes.default.svc
    namespace: springboot-app

  syncPolicy:
    automated:
      prune: true
      selfHeal: true

    syncOptions:
      - CreateNamespace=true